theme: jekyll-theme-minimal
title: Todd Peters - Product Manager
description: Tailored resumes for specific opportunities

# Prevent search engine indexing
plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default
      robots: noindex, nofollow
